### ISSUE TITLE
RuntimeError: `HDR-FI` can not handle the given uri.` error when reading 'data/neural_pil/BRDFLut.hdr'

### ISSUE THREAD

**Issue by SherifGabr** [google/samurai#2]
```
Traceback (most recent call last):
  File "/projappl/project_2007011/miniconda3/envs/samurai/lib/python3.9/site-packages/imageio/core/imopen.py", line 149, in imopen
    return config.plugin_class(request, **kwargs)
  File "/projappl/project_2007011/miniconda3/envs/samurai/lib/python3.9/site-packages/imageio/config/plugins.py", line 108, in partial_legacy_plugin
    return LegacyPlugin(request, legacy_plugin)
  File "/projappl/project_2007011/miniconda3/envs/samurai/lib/python3.9/site-packages/imageio/core/legacy_plugin_wrapper.py", line 63, in __init__
    raise InitializationError(
imageio.core.request.InitializationError: `HDR-FI` can not read `data/neural_pil/BRDFLut.hdr`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/project_2007011/samurai/train_samurai.py", line 1442, in <module>
    main(args)
  File "/scratch/project_2007011/samurai/train_samurai.py", line 129, in main
    samurai = SamuraiModel(
  File "/scratch/project_2007011/samurai/models/samurai/samurai_model.py", line 69, in __init__
    self.fine_model = FineModel(args, **kwargs)
  File "/scratch/project_2007011/samurai/models/samurai/models.py", line 338, in __init__
    self.renderer = PreintegratedRenderer(
  File "/scratch/project_2007011/samurai/nn_utils/preintegrated_rendering.py", line 34, in __init__
    brdf_map = imageio.imread(brdf_integration_map_path, format='HDR-FI')
  File "/projappl/project_2007011/miniconda3/envs/samurai/lib/python3.9/site-packages/imageio/core/functions.py", line 159, in imread
    with imopen(uri, "ri", plugin=format) as file:
  File "/projappl/project_2007011/miniconda3/envs/samurai/lib/python3.9/site-packages/imageio/core/imopen.py", line 167, in imopen
    raise err_type(err_msg) from err_from
RuntimeError: `HDR-FI` can not handle the given uri.
```

`HDR-FI` cannot read the file. I have tried resolving the issue by replacing `format` with `format_hint` and replacing `format="HDR-FI"` with `format=".hdr"` but all failed.

**Comment by andreasEngelhardt** [comment]
Hey,
most likely this is due to a missing plugin for imageio. It is assumed that "freeimage" is installed which unfortunately isn't reflected in the environment.yml. On top of that imageio did some changes in the version referenced as requirement that makes it hard to install the plugin from within imageio itself.
I'd suggest updating imageio and then trying to call `imageio.plugins.freeimage.download()` in a python shell. If it still doesn't work, please report back.

**Comment by SherifGabr** [comment]
Seems to be a missing binary issue. I uncommented line 32 in `nn_utils/preintegrated_rendering.py` and it works now.
I was just writing to update when I saw your comment. Thanks!
