### ISSUE TITLE
tensorflow/python/framework/ops.py", line 7186, in raise_from_not_ok_status     raise core._status_to_exception(e) from None  # pylint: disable=protected-access tensorflow.python.framework.errors_impl.InvalidArgumentError: Batch size must be greater than zero. [Op:BatchDatasetV2] while batch_size is set to 1024 by default

### ISSUE THREAD

**Issue by monajalal** [google/samurai#9]
While I am aware of the libcudnn problem, the training continued but at the end I got the error you see below. All the steps before this step went through with no problem. Please let me know what your thoughts are on both libcudnn problem as well as the main error.
```
(samurai) mona@ard-gpu-01:~/samurai$ python train_samurai.py --config configs/samurai/samurai.txt --datadir data/duck/ --basedir . --expname duck_test --gpu 0
Namespace(config=None, basedir='.', expname='duck_test', batch_size=1024, learning_rate=0.0001, epochs=150, steps_per_epoch=2000, gpu='0', tpu=None, debug=False, profile=False, perturb=1.0, raw_noise_std=0.0, coarse_samples=64, linear_disparity_sampling=False, fine_samples=128, fourier_frequency=10, direction_fourier_frequency=4, random_encoding_offsets=True, fine_net_width=128, fine_net_depth=8, coarse_net_width=128, coarse_net_depth=6, appearance_latent_dim=32, diffuse_latent_dim=24, fix_diffuse=True, camera_distribution='sphere', use_fully_random_cameras=False, random_cameras_per_view=4, min_softmax_scaler=1.0, max_softmax_scaler=10.0, camera_weight_update_lr=0.3, camera_weight_update_momentum=0.75, bounding_size=0.5, resolution_factor=4, advanced_loss_done=80000, network_gradient_norm_clipping=0.1, camera_gradient_norm_clipping=-1, not_learn_r=False, not_learn_t=False, not_learn_f=False, edge_align_step=200, num_edge_align_steps=50, pretrained_camera_poses_folder=None, start_f_optimization=90000, start_fourier_anneal=0, finish_fourier_anneal=50000, slow_scheduler_decay=100000, brdf_schedule_decay=40000, lambda_smoothness=0.01, smoothness_bound_dividier=200, coarse_distortion_lambda=0.001, fine_distortion_lambda=0, normal_direction_lambda=0.005, mlp_normal_direction_lambda=0.0003, disable_posterior_scaling=False, disable_mask_uncertainty=True, lambda_brdf_decoder_smoothness=0.1, lambda_brdf_decoder_sparsity=0.01, camera_lr=0.003, camera_lr_decay=70, camera_regularization=0.1, aim_center_regularization=10.0, camera_rotation='lookat', learn_camera_offsets=True, basecolor_metallic=True, skip_decomposition=False, compose_on_white=True, rotating_object=False, single_env=False, brdf_preintegration_path='data/neural_pil/BRDFLut.hdr', illumination_network_path='data/neural_pil/illumination-network', datadir='data/duck/', max_resolution_dimension=400, test_holdout=16, dataset='samurai', load_gt_poses=False, canonical_pose=0, log_step=100, weights_epoch=5, validation_epoch=5, testset_epoch=150, video_epoch=50, lrate_decay=300, render_only=False)
2023-06-21 08:35:27.209395: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-06-21 08:35:27.246961: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib:/home/mona/MVTec/HALCON-23.05-Progress//lib/x64-linux:/usr/local/cuda-11.7/lib64:/home/mona/onnx-tensorrt/build:
2023-06-21 08:35:27.246980: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
Utilizing 0 GPUs for training.
2023-06-21 08:35:28.412840: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
(70, 3)
Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 MappingNetwork/Layer_0 (Den  (None, 128)              16512     
 se)                                                             
                                                                 
 MappingNetwork/Layer_1 (Den  (None, 128)              16512     
 se)                                                             
                                                                 
 MappingNetwork/Final (Dense  (None, 768)              99072     
 )                                                               
                                                                 
 reshape_1 (Reshape)         (None, 2, 3, 128)         0         
                                                                 
=================================================================
Total params: 132,096
Trainable params: 132,096
Non-trainable params: 0
_________________________________________________________________
Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
=================================================================
 ConditionalNetwork/Dense1 (  (None, 32)               192       
 Dense)                                                          
                                                                 
 ConditionalNetwork/DenseFin  (None, 256)              8448      
 al (Dense)                                                      
                                                                 
 reshape_2 (Reshape)         (None, 2, 128)            0         
                                                                 
=================================================================
Total params: 8,640
Trainable params: 8,640
Non-trainable params: 0
_________________________________________________________________
Found ckpts []
Starting training in epoch 0 at step 0
Start Training...
/home/mona/anaconda3/envs/samurai/lib/python3.9/site-packages/tensorflow/python/framework/indexed_slices.py:444: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradients/interpolate_bilinear/gather-bottom_right/GatherV2_grad/Reshape_1:0", shape=(1024,), dtype=int32), values=Tensor("gradients/interpolate_bilinear/gather-bottom_right/GatherV2_grad/Reshape:0", shape=(1024, 1), dtype=float32), dense_shape=Tensor("gradients/interpolate_bilinear/gather-bottom_right/GatherV2_grad/Cast:0", shape=(2,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(
/home/mona/anaconda3/envs/samurai/lib/python3.9/site-packages/tensorflow/python/framework/indexed_slices.py:444: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradients/interpolate_bilinear/gather-bottom_left/GatherV2_grad/Reshape_1:0", shape=(1024,), dtype=int32), values=Tensor("gradients/interpolate_bilinear/gather-bottom_left/GatherV2_grad/Reshape:0", shape=(1024, 1), dtype=float32), dense_shape=Tensor("gradients/interpolate_bilinear/gather-bottom_left/GatherV2_grad/Cast:0", shape=(2,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(
/home/mona/anaconda3/envs/samurai/lib/python3.9/site-packages/tensorflow/python/framework/indexed_slices.py:444: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradients/interpolate_bilinear/gather-top_right/GatherV2_grad/Reshape_1:0", shape=(1024,), dtype=int32), values=Tensor("gradients/interpolate_bilinear/gather-top_right/GatherV2_grad/Reshape:0", shape=(1024, 1), dtype=float32), dense_shape=Tensor("gradients/interpolate_bilinear/gather-top_right/GatherV2_grad/Cast:0", shape=(2,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(
/home/mona/anaconda3/envs/samurai/lib/python3.9/site-packages/tensorflow/python/framework/indexed_slices.py:444: UserWarning: Converting sparse IndexedSlices(IndexedSlices(indices=Tensor("gradients/interpolate_bilinear/gather-top_left/GatherV2_grad/Reshape_1:0", shape=(1024,), dtype=int32), values=Tensor("gradients/interpolate_bilinear/gather-top_left/GatherV2_grad/Reshape:0", shape=(1024, 1), dtype=float32), dense_shape=Tensor("gradients/interpolate_bilinear/gather-top_left/GatherV2_grad/Cast:0", shape=(2,), dtype=int32))) to a dense Tensor of unknown shape. This may consume a large amount of memory.
  warnings.warn(
2000/2000 [==============================] - 2948s 1s/step - loss: 1.5832 - loss_camera: 7.4645 - fine_loss: 1.8258
Rendering last datapoint
Traceback (most recent call last):
  File "/home/mona/samurai/train_samurai.py", line 1442, in <module>
    main(args)
  File "/home/mona/samurai/train_samurai.py", line 536, in main
    render_full_datapoint(
  File "/home/mona/samurai/train_samurai.py", line 739, in render_full_datapoint
    fine_result = samurai.distributed_call(
  File "/home/mona/samurai/models/samurai/samurai_model.py", line 361, in distributed_call
    tf.data.Dataset.from_tensor_slices(
  File "/home/mona/anaconda3/envs/samurai/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1714, in batch
    return BatchDataset(self, batch_size, drop_remainder, name=name)
  File "/home/mona/anaconda3/envs/samurai/lib/python3.9/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 4897, in __init__
    variant_tensor = gen_dataset_ops.batch_dataset_v2(
  File "/home/mona/anaconda3/envs/samurai/lib/python3.9/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 685, in batch_dataset_v2
    _ops.raise_from_not_ok_status(e, name)
  File "/home/mona/anaconda3/envs/samurai/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 7186, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Batch size must be greater than zero. [Op:BatchDatasetV2]
```

**Comment by monajalal** [comment]
```
(base) mona@ard-gpu-01:~/samurai$ ldconfig -N -v $(sed 's/:/ /g' <<< $LD_LIBRARY_PATH) 2>/dev/null | grep libcudnn
libcudnn.so.8 -> libcudnn.so.8.7.0
libcudnn_cnn_infer.so.8 -> libcudnn_cnn_infer.so.8.7.0
libcudnn_ops_train.so.8 -> libcudnn_ops_train.so.8.7.0
libcudnn_adv_train.so.8 -> libcudnn_adv_train.so.8.7.0
libcudnn_ops_infer.so.8 -> libcudnn_ops_infer.so.8.7.0
libcudnn_cnn_train.so.8 -> libcudnn_cnn_train.so.8.7.0
libcudnn_adv_infer.so.8 -> libcudnn_adv_infer.so.8.7.0
```
